
import React, { useState } from 'react';
import { X, Mail, Copy, Shield, Download } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { toast } from '@/hooks/use-toast';

interface TakedownGeneratorProps {
  scanResult: {
    hash: string;
    timestamp: string;
    status: string;
    confidence: number;
  };
  onClose: () => void;
}

const TakedownGenerator: React.FC<TakedownGeneratorProps> = ({ scanResult, onClose }) => {
  const [formData, setFormData] = useState({
    yourName: '',
    yourEmail: '',
    relationship: 'myself',
    platformUrl: '',
    description: ''
  });
  const [generatedContent, setGeneratedContent] = useState('');

  const generateTakedownRequest = () => {
    const template = `
Subject: URGENT: DMCA Takedown Request - Unauthorized/Manipulated Image Content

Dear Platform Security Team,

I am writing to submit a formal DMCA takedown request for content that violates my privacy rights and potentially contains manipulated or deepfaked imagery.

INCIDENT DETAILS:
━━━━━━━━━━━━━━━━━━━━━
• Content URL: ${formData.platformUrl}
• Violation Type: ${scanResult.status.toUpperCase()}
• Detection Confidence: ${scanResult.confidence}%
• Scan Reference: ${scanResult.hash}
• Detection Timestamp: ${new Date(scanResult.timestamp).toLocaleString()}

COMPLAINANT INFORMATION:
━━━━━━━━━━━━━━━━━━━━━━━━
• Name: ${formData.yourName}
• Email: ${formData.yourEmail}
• Relationship to Subject: ${formData.relationship === 'myself' ? 'I am the subject in the image' : 'I am acting on behalf of the subject'}

VIOLATION DESCRIPTION:
━━━━━━━━━━━━━━━━━━━━━━━
${formData.description || 'This content contains my image that has been used without permission and may have been manipulated using AI technology. This violates my privacy rights and potentially constitutes harassment.'}

TECHNICAL EVIDENCE:
━━━━━━━━━━━━━━━━━━━━━━
This content was analyzed using NERA (Nameera AI Protection System), which detected:
- ${scanResult.status === 'deepfake' ? 'AI-generated deepfake content' : 'Unauthorized image manipulation'}
- Confidence level: ${scanResult.confidence}%
- Technical hash for verification: ${scanResult.hash}

LEGAL BASIS:
━━━━━━━━━━━━━
• DMCA Section 512(c)
• Right to Privacy
• Non-consensual intimate imagery laws (where applicable)
• Platform Terms of Service violations

I HEREBY STATE:
━━━━━━━━━━━━━━━━
1. I have a good faith belief that the use of this content is not authorized
2. The information in this notification is accurate
3. Under penalty of perjury, I am authorized to act on behalf of the rights holder

REQUESTED ACTION:
━━━━━━━━━━━━━━━━━━━
• Immediate removal of the infringing content
• Suspension of the account that posted this content
• Prevention of re-uploading similar content

Please confirm receipt of this request and provide a timeline for content removal.

With respect and urgency,
${formData.yourName}

Generated by NERA Protection System
"Made with love, for the love of Nameera"
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    `.trim();

    setGeneratedContent(template);
    toast({
      title: "🛡️ Legal Shield Generated",
      description: "Your takedown request is ready to protect her dignity.",
    });
  };

  const copyToClipboard = () => {
    navigator.clipboard.writeText(generatedContent);
    toast({
      title: "📋 Copied to Clipboard",
      description: "You can now paste this into your email or report form.",
    });
  };

  const downloadAsFile = () => {
    const blob = new Blob([generatedContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `nera-takedown-request-${scanResult.hash}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);

    toast({
      title: "💾 Downloaded Successfully",
      description: "Your takedown request has been saved as a file.",
    });
  };

  return (
    <Card className="bg-white/95 backdrop-blur-sm border-violet-200 shadow-xl">
      <CardHeader className="border-b border-violet-200">
        <div className="flex items-center justify-between">
          <div className="flex items-center space-x-3">
            <Shield className="h-6 w-6 text-violet-600" />
            <CardTitle className="text-2xl font-light text-violet-900 font-serif">
              Legal Protection Shield
            </CardTitle>
          </div>
          <Button variant="ghost" size="sm" onClick={onClose}>
            <X className="h-4 w-4" />
          </Button>
        </div>
        <p className="text-violet-600">
          NERA will help you generate a professional takedown request to protect dignity and honor.
        </p>
      </CardHeader>
      
      <CardContent className="p-6 space-y-6">
        {!generatedContent ? (
          <div className="space-y-4">
            <div className="grid md:grid-cols-2 gap-4">
              <div>
                <Label htmlFor="yourName" className="text-violet-700 font-medium">Your Full Name *</Label>
                <Input
                  id="yourName"
                  value={formData.yourName}
                  onChange={(e) => setFormData(prev => ({...prev, yourName: e.target.value}))}
                  placeholder="Enter your legal name"
                  className="border-violet-300 focus:border-violet-500"
                />
              </div>
              
              <div>
                <Label htmlFor="yourEmail" className="text-violet-700 font-medium">Your Email *</Label>
                <Input
                  id="yourEmail"
                  type="email"
                  value={formData.yourEmail}
                  onChange={(e) => setFormData(prev => ({...prev, yourEmail: e.target.value}))}
                  placeholder="your.email@example.com"
                  className="border-violet-300 focus:border-violet-500"
                />
              </div>
            </div>

            <div>
              <Label htmlFor="platformUrl" className="text-violet-700 font-medium">Platform URL *</Label>
              <Input
                id="platformUrl"
                value={formData.platformUrl}
                onChange={(e) => setFormData(prev => ({...prev, platformUrl: e.target.value}))}
                placeholder="https://platform.com/post/12345"
                className="border-violet-300 focus:border-violet-500"
              />
              <p className="text-sm text-violet-500 mt-1">
                Direct link to where the violating content is posted
              </p>
            </div>

            <div>
              <Label htmlFor="description" className="text-violet-700 font-medium">Additional Description</Label>
              <Textarea
                id="description"
                value={formData.description}
                onChange={(e) => setFormData(prev => ({...prev, description: e.target.value}))}
                placeholder="Describe how this content violates your rights (optional - NERA will provide a default description)"
                rows={3}
                className="border-violet-300 focus:border-violet-500"
              />
            </div>

            <div className="flex justify-center">
              <Button
                onClick={generateTakedownRequest}
                disabled={!formData.yourName || !formData.yourEmail || !formData.platformUrl}
                className="bg-gradient-to-r from-violet-500 to-purple-600 hover:from-violet-600 hover:to-purple-700 text-white px-8 py-3 rounded-full"
              >
                <Shield className="h-5 w-5 mr-2" />
                Generate Legal Protection
              </Button>
            </div>
          </div>
        ) : (
          <div className="space-y-4">
            <div className="bg-violet-50 border border-violet-200 rounded-lg p-4">
              <h4 className="font-medium text-violet-800 mb-2">🛡️ Your Legal Shield is Ready</h4>
              <p className="text-violet-600 text-sm">
                This professional takedown request includes technical evidence from NERA's scan 
                and follows legal DMCA guidelines.
              </p>
            </div>

            <div className="bg-gray-50 border border-gray-200 rounded-lg p-4 max-h-96 overflow-y-auto">
              <pre className="text-sm text-gray-800 whitespace-pre-wrap font-mono leading-relaxed">
                {generatedContent}
              </pre>
            </div>

            <div className="flex flex-wrap gap-3 justify-center">
              <Button
                onClick={copyToClipboard}
                variant="outline"
                className="border-violet-300 text-violet-600 hover:bg-violet-50"
              >
                <Copy className="h-4 w-4 mr-2" />
                Copy Text
              </Button>

              <Button
                onClick={downloadAsFile}
                variant="outline"
                className="border-violet-300 text-violet-600 hover:bg-violet-50"
              >
                <Download className="h-4 w-4 mr-2" />
                Download File
              </Button>

              <Button
                onClick={() => setGeneratedContent('')}
                className="bg-gradient-to-r from-violet-500 to-purple-600 hover:from-violet-600 hover:to-purple-700 text-white"
              >
                Generate New Request
              </Button>
            </div>

            <div className="text-center p-4 bg-green-50 rounded-lg border border-green-200">
              <p className="text-green-700 text-sm">
                <strong>Next Steps:</strong> Send this to the platform's abuse/legal team, 
                or use their DMCA reporting form. Keep a copy for your records.
              </p>
            </div>
          </div>
        )}
      </CardContent>
    </Card>
  );
};

export default TakedownGenerator;
